app:
  name: 'L0'
  version: '1.0'

postgres:
  host: '127.0.0.1'
  port: '5432'
  user: 'postgres'
  password: '1234'
  name: 'db_wb'
  pg_driver: 'pq'

http:
  host: 'localhost'
  port: '8000'

nats:
  host: '0.0.0.0'
  port: '4222'
  cluster: 'test-cluster'
  client: 'event-listener'
  topic: 'main-chanel'